"""empty message

Revision ID: 038e1bab4f92
Revises: e9bfb822747e
Create Date: 2026-03-03 18:57:25.437697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038e1bab4f92'
down_revision = 'e9bfb822747e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('courses_faculty_id_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'users', ['faculty_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_faculty_id_fkey'), 'courses', 'users', ['faculty_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
