"""empty message

Revision ID: 0c3f99e68037
Revises: 037264aac9e7
Create Date: 2026-02-23 12:08:38.153078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3f99e68037'
down_revision = '037264aac9e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_activated', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_activated')
    # ### end Alembic commands ###
