"""empty message

Revision ID: 27eb180005cb
Revises: 29225f94cd7c
Create Date: 2026-02-19 12:25:58.431140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27eb180005cb'
down_revision = '29225f94cd7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculties', sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'USER', 'ANY', 'OPTIONAL', name='roletype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculties', 'role')
    # ### end Alembic commands ###
