"""empty message

Revision ID: 29225f94cd7c
Revises: 333fb01f7dbf
Create Date: 2026-02-19 12:25:31.966795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29225f94cd7c'
down_revision = '333fb01f7dbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'USER', 'ANY', 'OPTIONAL', name='roletype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'role')
    # ### end Alembic commands ###
