"""empty message

Revision ID: 333fb01f7dbf
Revises: 7fa41ff5d127
Create Date: 2026-02-19 12:24:11.552698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333fb01f7dbf'
down_revision = '7fa41ff5d127'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('course_credit', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_course_name'), 'courses', ['course_name'], unique=False)
    op.create_table('faculties',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('hashed_pass', sa.String(), nullable=False),
    sa.Column('dept_name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculties_email'), 'faculties', ['email'], unique=True)
    op.create_index(op.f('ix_faculties_first_name'), 'faculties', ['first_name'], unique=False)
    op.create_index(op.f('ix_faculties_last_name'), 'faculties', ['last_name'], unique=False)
    op.create_index(op.f('ix_faculties_phone'), 'faculties', ['phone'], unique=True)
    op.create_table('students',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('hashed_pass', sa.String(), nullable=False),
    sa.Column('dob', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_first_name'), 'students', ['first_name'], unique=False)
    op.create_index(op.f('ix_students_last_name'), 'students', ['last_name'], unique=False)
    op.create_index(op.f('ix_students_phone'), 'students', ['phone'], unique=True)
    op.create_table('association',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_student_course')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_index(op.f('ix_students_phone'), table_name='students')
    op.drop_index(op.f('ix_students_last_name'), table_name='students')
    op.drop_index(op.f('ix_students_first_name'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_faculties_phone'), table_name='faculties')
    op.drop_index(op.f('ix_faculties_last_name'), table_name='faculties')
    op.drop_index(op.f('ix_faculties_first_name'), table_name='faculties')
    op.drop_index(op.f('ix_faculties_email'), table_name='faculties')
    op.drop_table('faculties')
    op.drop_index(op.f('ix_courses_course_name'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
