"""empty message

Revision ID: 35ea9eaa4832
Revises: e2f127813ddf
Create Date: 2026-02-23 17:56:02.357612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ea9eaa4832'
down_revision = 'e2f127813ddf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('faculty_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'courses', 'users', ['faculty_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'faculty_id')
    # ### end Alembic commands ###
