"""empty message

Revision ID: 38f4ee31c7ce
Revises: ef934446d1f4
Create Date: 2026-02-19 16:34:00.277632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f4ee31c7ce'
down_revision = 'ef934446d1f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('association_course_id_fkey'), 'association', type_='foreignkey')
    op.drop_constraint(op.f('association_student_id_fkey'), 'association', type_='foreignkey')
    op.create_foreign_key(None, 'association', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'association', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.add_column('courses', sa.Column('faculty_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'courses', 'faculties', ['faculty_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_faculty_id_fkey', 'courses', type_='foreignkey')
    op.drop_column('courses', 'faculty_id')
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.create_foreign_key(op.f('association_student_id_fkey'), 'association', 'students', ['student_id'], ['id'])
    op.create_foreign_key(op.f('association_course_id_fkey'), 'association', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###
