"""empty message

Revision ID: 3b4a52cfdaf2
Revises: f5f082601b0a
Create Date: 2026-02-24 13:45:53.803453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '3b4a52cfdaf2'
down_revision = 'f5f082601b0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_translations',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('language_code', postgresql.ENUM('EN', 'HI', name='languageenum', create_type=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'language_code', name='uq_course_language')
    )
    op.create_index(op.f('ix_course_translations_course_name'), 'course_translations', ['course_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_translations_course_name'), table_name='course_translations')
    op.drop_table('course_translations')
    # ### end Alembic commands ###
