"""empty message

Revision ID: 4cdb98e8a79c
Revises: eff30e923e47
Create Date: 2026-03-03 10:41:07.558541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cdb98e8a79c'
down_revision = 'eff30e923e47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('enrolled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('association', 'enrolled_at')
    # ### end Alembic commands ###
