"""empty message

Revision ID: 53be0470deac
Revises: 8004b4e8ff62
Create Date: 2026-02-24 15:40:49.146930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53be0470deac'
down_revision = '8004b4e8ff62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'language_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('language_code', postgresql.ENUM('en', 'hi', name='languageenum'), server_default=sa.text("'en'::languageenum"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
