"""empty message

Revision ID: 7203e8a8c5b1
Revises: 3b4a52cfdaf2
Create Date: 2026-02-24 13:59:49.755470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7203e8a8c5b1'
down_revision = '3b4a52cfdaf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_language', sa.Enum('EN', 'HI', name='languageenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    # ### end Alembic commands ###
