"""empty message

Revision ID: 8004b4e8ff62
Revises: 7203e8a8c5b1
Create Date: 2026-02-24 15:16:58.744635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8004b4e8ff62'
down_revision = '7203e8a8c5b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_language', sa.Enum('EN', 'HI', name='languageenum'), nullable=True))
    op.drop_column('users', 'preffered_language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preffered_language', postgresql.ENUM('en', 'hi', name='languageenum'), autoincrement=False, nullable=True))
    op.drop_column('users', 'preferred_language')
    # ### end Alembic commands ###
