"""empty message

Revision ID: af608dfd772a
Revises: 27eb180005cb
Create Date: 2026-02-19 13:26:06.460773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af608dfd772a'
down_revision = '27eb180005cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'STAFF', 'USER', 'ANY', 'OPTIONAL', name='roletype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ADMIN', 'STAFF', 'USER', 'ANY', 'OPTIONAL', name='roletype'),
               existing_nullable=False)
    # ### end Alembic commands ###
