"""empty message

Revision ID: c7e353463c1e
Revises: 0c3f99e68037
Create Date: 2026-02-23 12:40:12.096151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e353463c1e'
down_revision = '0c3f99e68037'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('course_credit', sa.Integer(), nullable=False),
    sa.Column('course_description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_course_name'), 'courses', ['course_name'], unique=False)
    op.alter_column('users', 'is_activated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_activated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_courses_course_name'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
