"""empty message

Revision ID: ef934446d1f4
Revises: af608dfd772a
Create Date: 2026-02-19 13:29:43.032236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef934446d1f4'
down_revision = 'af608dfd772a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faculties', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'STAFF', 'USER', 'ANY', 'OPTIONAL', name='roletype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faculties', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ADMIN', 'STAFF', 'USER', 'ANY', 'OPTIONAL', name='roletype'),
               existing_nullable=False)
    # ### end Alembic commands ###
