"""empty message

Revision ID: f5f082601b0a
Revises: 35ea9eaa4832
Create Date: 2026-02-24 13:39:25.995581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f5f082601b0a'
down_revision = '35ea9eaa4832'
branch_labels = None
depends_on = None


language_enum = postgresql.ENUM(
    "en",
    "hi",
    name="languageenum"
)


def upgrade() -> None:
     # :one: Create ENUM type in PostgreSQL
    language_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('language_code', sa.Enum('en', 'hi', name='languageenum'), nullable=False, server_default="en"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'language_code')

        # :two: Drop ENUM type
    language_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
